import { Inter } from "next/font/google";
import "./globals.css";
import NextProvider from '@/utils/NextProvider'
import Provider from "@/components/AuthProvider/sessionprovider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
    <Provider>
      <NextProvider>
      {children}
      </NextProvider>
    </Provider>
      </body>
    </html>
  );
}
